import type { AvatarShape } from "../../src/generated/prisma/client";

export type SeedTheme = {
  name: string;
  slug: string;
  description: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  backgroundColor: string;
  surfaceColor: string;
  textColor: string;
  mutedTextColor: string;
  fontDisplay: string;
  fontBody: string;
  fontLetter: string;
  avatarDefaultShape: AvatarShape;
  cardStyle: string;
  buttonStyle: string;
  decorationConfig: Record<string, unknown>;
  animationConfig: Record<string, unknown>;
};

/**
 * 12 thèmes de base (Partie 3 §14, Partie 9 §3, Partie 12 §9).
 * Les quatre premiers sont les thèmes initiaux assignés à Monseralt,
 * Marion, Elema et Martin ; les huit suivants complètent la
 * bibliothèque pour les profils futurs.
 */
export const SEED_THEMES: SeedTheme[] = [
  {
    name: "Lavande Nature",
    slug: "lavender-nature",
    description: "Lavande, blanc cassé, papillons et nature — doux et élégant.",
    primaryColor: "#9B87C4",
    secondaryColor: "#F5F1EA",
    accentColor: "#7A6BA5",
    backgroundColor: "#F7F4FB",
    surfaceColor: "rgba(255,255,255,0.55)",
    textColor: "#3B3450",
    mutedTextColor: "#8A82A0",
    fontDisplay: "'Cormorant Garamond', serif",
    fontBody: "'Inter', sans-serif",
    fontLetter: "'Cormorant Garamond', serif",
    avatarDefaultShape: "CIRCLE",
    cardStyle: "glass-soft",
    buttonStyle: "rounded",
    decorationConfig: { motifs: ["butterflies", "leaves"], density: "low" },
    animationConfig: { style: "float", intensity: "gentle" },
  },
  {
    name: "Papillons Étoilés",
    slug: "starry-butterfly",
    description: "Bleu nuit doux, étoiles et papillons — simple et lumineux.",
    primaryColor: "#3E5C89",
    secondaryColor: "#E8F1FC",
    accentColor: "#F0C24B",
    backgroundColor: "#F3F7FD",
    surfaceColor: "rgba(255,255,255,0.6)",
    textColor: "#1F2D40",
    mutedTextColor: "#5B7089",
    fontDisplay: "'Poppins', sans-serif",
    fontBody: "'Inter', sans-serif",
    fontLetter: "'Poppins', sans-serif",
    avatarDefaultShape: "STAR",
    cardStyle: "glass-soft",
    buttonStyle: "rounded",
    decorationConfig: { motifs: ["stars", "butterflies"], density: "medium" },
    animationConfig: { style: "twinkle", intensity: "gentle" },
  },
  {
    name: "Cœur Sombre",
    slug: "dark-heart",
    description: "Bordeaux, violet profond, cœurs et écriture manuscrite.",
    primaryColor: "#8C2F45",
    secondaryColor: "#2C1B30",
    accentColor: "#D88AA0",
    backgroundColor: "#1B1220",
    surfaceColor: "rgba(255,255,255,0.07)",
    textColor: "#F3E7EC",
    mutedTextColor: "#B79AA8",
    fontDisplay: "'Playfair Display', serif",
    fontBody: "'Inter', sans-serif",
    fontLetter: "'Dancing Script', cursive",
    avatarDefaultShape: "HEART",
    cardStyle: "glass-dark",
    buttonStyle: "rounded",
    decorationConfig: { motifs: ["hearts"], density: "low" },
    animationConfig: { style: "glow", intensity: "gentle" },
  },
  {
    name: "Élégance Géométrique",
    slug: "elegant-geometric",
    description: "Graphite, argent, géométrie — sobre et moderne.",
    primaryColor: "#2B2E33",
    secondaryColor: "#C7CCD1",
    accentColor: "#8A94A6",
    backgroundColor: "#101214",
    surfaceColor: "rgba(255,255,255,0.05)",
    textColor: "#EDEFF2",
    mutedTextColor: "#9AA1AB",
    fontDisplay: "'Space Grotesk', sans-serif",
    fontBody: "'Inter', sans-serif",
    fontLetter: "'Space Grotesk', sans-serif",
    avatarDefaultShape: "HEXAGON",
    cardStyle: "glass-dark",
    buttonStyle: "sharp",
    decorationConfig: { motifs: ["geometry"], density: "low" },
    animationConfig: { style: "depth", intensity: "subtle" },
  },
  {
    name: "Floral Doux",
    slug: "soft-floral",
    description: "Rose tendre et fleurs discrètes.",
    primaryColor: "#E8A0BC",
    secondaryColor: "#FFF6F5",
    accentColor: "#D97BA0",
    backgroundColor: "#FFF9FA",
    surfaceColor: "rgba(255,255,255,0.6)",
    textColor: "#4A2A38",
    mutedTextColor: "#9C7480",
    fontDisplay: "'Playfair Display', serif",
    fontBody: "'Inter', sans-serif",
    fontLetter: "'Cormorant Garamond', serif",
    avatarDefaultShape: "OVAL",
    cardStyle: "glass-soft",
    buttonStyle: "rounded",
    decorationConfig: { motifs: ["flowers"], density: "medium" },
    animationConfig: { style: "float", intensity: "gentle" },
  },
  {
    name: "Nuit Étoilée",
    slug: "night-sky",
    description: "Ciel nocturne profond, étoiles dorées.",
    primaryColor: "#2E4374",
    secondaryColor: "#0E1830",
    accentColor: "#F4C95D",
    backgroundColor: "#0E1830",
    surfaceColor: "rgba(255,255,255,0.06)",
    textColor: "#EDEFFA",
    mutedTextColor: "#9FAAC7",
    fontDisplay: "'Playfair Display', serif",
    fontBody: "'Inter', sans-serif",
    fontLetter: "'Playfair Display', serif",
    avatarDefaultShape: "STAR",
    cardStyle: "glass-dark",
    buttonStyle: "rounded",
    decorationConfig: { motifs: ["stars"], density: "high" },
    animationConfig: { style: "twinkle", intensity: "medium" },
  },
  {
    name: "Océan",
    slug: "ocean",
    description: "Bleu-vert apaisant, lumière dorée.",
    primaryColor: "#1D7A8C",
    secondaryColor: "#DCF3F5",
    accentColor: "#F2A65A",
    backgroundColor: "#F1FAFB",
    surfaceColor: "rgba(255,255,255,0.55)",
    textColor: "#123138",
    mutedTextColor: "#4E7C85",
    fontDisplay: "'Poppins', sans-serif",
    fontBody: "'Inter', sans-serif",
    fontLetter: "'Poppins', sans-serif",
    avatarDefaultShape: "CIRCLE",
    cardStyle: "glass-soft",
    buttonStyle: "rounded",
    decorationConfig: { motifs: ["waves"], density: "low" },
    animationConfig: { style: "drift", intensity: "gentle" },
  },
  {
    name: "Cristal",
    slug: "crystal",
    description: "Blanc glacé, reflets translucides.",
    primaryColor: "#9AD1D4",
    secondaryColor: "#F5FBFB",
    accentColor: "#C9A6E0",
    backgroundColor: "#FBFEFE",
    surfaceColor: "rgba(255,255,255,0.65)",
    textColor: "#2C3E40",
    mutedTextColor: "#77999C",
    fontDisplay: "'Cormorant Garamond', serif",
    fontBody: "'Inter', sans-serif",
    fontLetter: "'Cormorant Garamond', serif",
    avatarDefaultShape: "DIAMOND",
    cardStyle: "glass-soft",
    buttonStyle: "pill",
    decorationConfig: { motifs: ["sparkles"], density: "low" },
    animationConfig: { style: "shimmer", intensity: "subtle" },
  },
  {
    name: "Minimaliste",
    slug: "minimal",
    description: "Épuré, sans décoration superflue.",
    primaryColor: "#333333",
    secondaryColor: "#FFFFFF",
    accentColor: "#666666",
    backgroundColor: "#FAFAFA",
    surfaceColor: "rgba(255,255,255,0.8)",
    textColor: "#1A1A1A",
    mutedTextColor: "#767676",
    fontDisplay: "'Inter', sans-serif",
    fontBody: "'Inter', sans-serif",
    fontLetter: "'Inter', sans-serif",
    avatarDefaultShape: "SQUARE_ROUNDED",
    cardStyle: "flat",
    buttonStyle: "sharp",
    decorationConfig: { motifs: [], density: "none" },
    animationConfig: { style: "fade", intensity: "subtle" },
  },
  {
    name: "Rose Pastel",
    slug: "rose-pastel",
    description: "Rose poudré, tendresse et légèreté.",
    primaryColor: "#E7B8C4",
    secondaryColor: "#FCEFEF",
    accentColor: "#C98A9C",
    backgroundColor: "#FFF7F8",
    surfaceColor: "rgba(255,255,255,0.6)",
    textColor: "#4A2E36",
    mutedTextColor: "#966E78",
    fontDisplay: "'Playfair Display', serif",
    fontBody: "'Inter', sans-serif",
    fontLetter: "'Dancing Script', cursive",
    avatarDefaultShape: "HEART",
    cardStyle: "glass-soft",
    buttonStyle: "pill",
    decorationConfig: { motifs: ["hearts", "flowers"], density: "low" },
    animationConfig: { style: "float", intensity: "gentle" },
  },
  {
    name: "Nature",
    slug: "nature",
    description: "Vert doux, feuillage et lumière naturelle.",
    primaryColor: "#5C8A57",
    secondaryColor: "#F1F6ED",
    accentColor: "#A3C586",
    backgroundColor: "#F7FAF3",
    surfaceColor: "rgba(255,255,255,0.6)",
    textColor: "#26361F",
    mutedTextColor: "#6C8262",
    fontDisplay: "'Cormorant Garamond', serif",
    fontBody: "'Inter', sans-serif",
    fontLetter: "'Cormorant Garamond', serif",
    avatarDefaultShape: "OVAL",
    cardStyle: "glass-soft",
    buttonStyle: "rounded",
    decorationConfig: { motifs: ["leaves"], density: "medium" },
    animationConfig: { style: "sway", intensity: "gentle" },
  },
  {
    name: "Moderne Sombre",
    slug: "modern-dark",
    description: "Contraste marqué, accent vif, ambiance nocturne moderne.",
    primaryColor: "#6C63FF",
    secondaryColor: "#1A1B26",
    accentColor: "#FF6584",
    backgroundColor: "#14151F",
    surfaceColor: "rgba(255,255,255,0.06)",
    textColor: "#E8E8F0",
    mutedTextColor: "#9497B0",
    fontDisplay: "'Space Grotesk', sans-serif",
    fontBody: "'Inter', sans-serif",
    fontLetter: "'Space Grotesk', sans-serif",
    avatarDefaultShape: "HEXAGON",
    cardStyle: "glass-dark",
    buttonStyle: "sharp",
    decorationConfig: { motifs: ["particles"], density: "low" },
    animationConfig: { style: "glow", intensity: "medium" },
  },
];
